MEMORY_V1_SAMPLES = {
    "memories": [
        {
            "name": "ai_summary",
            "content": "My AI assistant summarizes reports every morning before stand-up.",
            "tags": ["ai", "assistant", "sample"],
            "importance": 7,
            "source": "test",
            "timestamp": "2025-04-18T08:00:00Z",
        },
        {
            "name": "ai_mistake",
            "content": "It once booked a hotel instead of a flight when I asked for a trip.",
            "tags": ["ai", "mistake", "sample"],
            "importance": 6,
            "source": "test",
            "timestamp": "2025-04-18T08:01:00Z",
        },
        {
            "name": "booking_confusion",
            "content": "The AI assistant thought 'trip' meant hotel by default.",
            "tags": ["ai", "error", "sample"],
            "importance": 5,
            "source": "test",
            "timestamp": "2025-04-18T08:10:00Z"
          },
        {
            "name": "preferences_record",
            "content": "The assistant remembers I prefer morning meetings and dark mode.",
            "tags": ["ai", "preferences", "sample"],
            "importance": 8,
            "source": "test",
            "timestamp": "2025-04-18T08:02:00Z",
        },
        {
            "name": "blocked_meeting",
            "content": "The assistant blocked a 3PM meeting because it conflicted with a recurring break.",
            "tags": ["calendar", "conflict", "sample"],
            "importance": 5,
            "source": "test",
            "timestamp": "2025-04-18T08:03:00Z",
        },
        {
            "name": "snack_time",
            "content": "I like to take snack breaks at 3PM.",
            "tags": ["routine", "sample"],
            "importance": 2,
            "source": "test",
            "timestamp": "2025-04-18T08:10:00Z",
        },
        {
            "name": "project_deadline",
            "content": "The project deadline is November 15th.",
            "tags": ["important", "work", "sample"],
            "importance": 9,
            "source": "test",
            "timestamp": "2025-04-18T08:04:00Z",
        },
        {
            "name": "birthday_fact",
            "content": "My birthday is February 30th.",
            "tags": ["birthday", "sample"],
            "importance": 4,
            "source": "test",
            "timestamp": "2025-04-18T08:05:00Z",
        },
        {
            "name": "mom_birthday",
            "content": "Mom\u2019s birthday is May 5th.",
            "tags": ["birthday", "family", "sample"],
            "importance": 5,
            "source": "test",
            "timestamp": "2025-04-18T08:06:00Z",
        },
        {
            "name": "dentist_appt",
            "content": "I have a dentist appointment on July 12th.",
            "tags": ["health", "appointment", "sample"],
            "importance": 6,
            "source": "test",
            "timestamp": "2025-04-18T08:07:00Z",
        },
        {
            "name": "random_fact",
            "content": "Bananas are technically berries, but strawberries aren't.",
            "tags": ["funfact", "sample"],
            "importance": 3,
            "source": "test",
            "timestamp": "2025-04-18T08:08:00Z",
        },
        {
            "name": "movie_opinion",
            "content": "I thought the sequel was better than the original.",
            "tags": ["opinion", "entertainment", "sample"],
            "importance": 2,
            "source": "test",
            "timestamp": "2025-04-18T08:09:00Z",
        },
    ],
    "relations": {
        "ai_summary": ["ai_mistake"],
        "preferences_record": ["blocked_meeting"],
        "blocked_meeting": ["snack_time"],
        "ai_mistake": ["booking_confusion"],
        "project_deadline": [],
        "birthday_fact": [],
        "mom_birthday": [],
        "dentist_appt": [],
        "random_fact": [],
        "movie_opinion": [],
    },
}
